### ISSUE TITLE
Extra coordinates in BoM files

### ISSUE THREAD

**Issue by matear** [AusClimateService/bias-correction-data-release#3]
In the bias-adjustment-input directory the BOM files have extra coordinates, which causes multivariable calculations to fail because the grids are inconsistent.  

A quick fix is to drop them as follows

if ACS_model == 'BOM':
    sfcWindmax=sfcWindmax.reset_coords('height', drop=True)
    tasmax=tasmax.reset_coords('height', drop=True)
    hursmin=hursmin.reset_coords({'height','level_height','model_level_number','sigma'}, drop=True)

**Comment by DamienIrving** [comment]
Thanks, @matear.

I can get rid of the `level_height`, `model_level_number` and `sigma` coordinates because they aren't important, but I'm reluctant to remove the `height` coordinate as the height in meters is something the user might want to know.

**Comment by DamienIrving** [comment]
I've updated the dataset... I ended up getting rid of `height` as well.
